// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthLayoutImport } from './routes/_auth-layout'
import { Route as AppLayoutImport } from './routes/_app-layout'
import { Route as IndexImport } from './routes/index'
import { Route as AppLayoutAppIndexImport } from './routes/_app-layout.app/index'
import { Route as AuthLayoutAuthLoginImport } from './routes/_auth-layout.auth/login'
import { Route as AuthLayoutAuthRegisterIndexImport } from './routes/_auth-layout.auth/register/index'
import { Route as AuthLayoutAuthForgotPasswordIndexImport } from './routes/_auth-layout.auth/forgot-password/index'
import { Route as AppLayoutAppUserSaleIndexImport } from './routes/_app-layout.app/user-sale/index'
import { Route as AppLayoutAppUserMeSaleIndexImport } from './routes/_app-layout.app/user-me-sale/index'
import { Route as AppLayoutAppUserMeSaleBookingIndexImport } from './routes/_app-layout.app/user-me-sale-booking/index'
import { Route as AppLayoutAppUserMeSaleBookingHistoryIndexImport } from './routes/_app-layout.app/user-me-sale-booking-history/index'
import { Route as AppLayoutAppSettingsIndexImport } from './routes/_app-layout.app/settings/index'
import { Route as AppLayoutAppPremiumIndexImport } from './routes/_app-layout.app/premium/index'
import { Route as AppLayoutAppPostIndexImport } from './routes/_app-layout.app/post/index'
import { Route as AppLayoutAppNotificationIndexImport } from './routes/_app-layout.app/notification/index'
import { Route as AppLayoutAppContactUsIndexImport } from './routes/_app-layout.app/contact-us/index'
import { Route as AppLayoutAppChatIndexImport } from './routes/_app-layout.app/chat/index'
import { Route as AppLayoutAppCartIndexImport } from './routes/_app-layout.app/cart/index'
import { Route as AppLayoutAppBookingIndexImport } from './routes/_app-layout.app/booking/index'
import { Route as AppLayoutAppBookingHistoryIndexImport } from './routes/_app-layout.app/booking-history/index'
import { Route as AppLayoutAppProductProductLayoutImport } from './routes/_app-layout.app/product/_product-layout'
import { Route as AppLayoutAppUserSaleIdIndexImport } from './routes/_app-layout.app/user-sale/$id/index'
import { Route as AppLayoutAppUserMeSaleCreateIndexImport } from './routes/_app-layout.app/user-me-sale/create/index'
import { Route as AppLayoutAppUserMeSaleIdIndexImport } from './routes/_app-layout.app/user-me-sale/$id/index'
import { Route as AppLayoutAppUserMeSaleBookingCreateIndexImport } from './routes/_app-layout.app/user-me-sale-booking/create/index'
import { Route as AppLayoutAppUserMeSaleBookingIdIndexImport } from './routes/_app-layout.app/user-me-sale-booking/$id/index'
import { Route as AppLayoutAppUserMeSaleBookingHistoryIdIndexImport } from './routes/_app-layout.app/user-me-sale-booking-history/$id/index'
import { Route as AppLayoutAppSettingsWalletIndexImport } from './routes/_app-layout.app/settings/wallet/index'
import { Route as AppLayoutAppSettingsUpdateIndexImport } from './routes/_app-layout.app/settings/update/index'
import { Route as AppLayoutAppSettingsTermsIndexImport } from './routes/_app-layout.app/settings/terms/index'
import { Route as AppLayoutAppSettingsPolicyIndexImport } from './routes/_app-layout.app/settings/policy/index'
import { Route as AppLayoutAppSettingsOrderHistoryIndexImport } from './routes/_app-layout.app/settings/order-history/index'
import { Route as AppLayoutAppSettingsLanguageIndexImport } from './routes/_app-layout.app/settings/language/index'
import { Route as AppLayoutAppSettingsChangePasswordIndexImport } from './routes/_app-layout.app/settings/change-password/index'
import { Route as AppLayoutAppProductProductLayoutIndexImport } from './routes/_app-layout.app/product/_product-layout/index'
import { Route as AppLayoutAppBookingIdIndexImport } from './routes/_app-layout.app/booking/$id/index'
import { Route as AppLayoutAppBookingHistoryIdIndexImport } from './routes/_app-layout.app/booking-history/$id/index'
import { Route as AppLayoutAppChatChatIdChatLayoutImport } from './routes/_app-layout.app/chat/$chatId/_chat-layout'
import { Route as AppLayoutAppUserMeSaleIdEditIndexImport } from './routes/_app-layout.app/user-me-sale/$id/edit/index'
import { Route as AppLayoutAppUserMeSaleBookingIdEditIndexImport } from './routes/_app-layout.app/user-me-sale-booking/$id/edit/index'
import { Route as AppLayoutAppUserMeSaleBookingHistoryIdAcceptIndexImport } from './routes/_app-layout.app/user-me-sale-booking-history/$id/accept/index'
import { Route as AppLayoutAppSettingsWalletDepositIndexImport } from './routes/_app-layout.app/settings/wallet/deposit/index'
import { Route as AppLayoutAppSettingsOrderHistoryIdIndexImport } from './routes/_app-layout.app/settings/order-history/$id/index'
import { Route as AppLayoutAppProductProductLayoutIdIndexImport } from './routes/_app-layout.app/product/_product-layout/$id/index'
import { Route as AppLayoutAppPostUserIdIndexImport } from './routes/_app-layout.app/post/user/$id/index'
import { Route as AppLayoutAppChatChatIdChatLayoutIndexImport } from './routes/_app-layout.app/chat/$chatId/_chat-layout/index'
import { Route as AppLayoutAppBookingIdFormIndexImport } from './routes/_app-layout.app/booking/$id/form/index'

// Create/Update Routes

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutRoute = AppLayoutImport.update({
  id: '/_app-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AppLayoutAppIndexRoute = AppLayoutAppIndexImport.update({
  path: '/app/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AuthLayoutAuthLoginRoute = AuthLayoutAuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const AuthLayoutAuthRegisterIndexRoute =
  AuthLayoutAuthRegisterIndexImport.update({
    path: '/auth/register/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AuthLayoutAuthForgotPasswordIndexRoute =
  AuthLayoutAuthForgotPasswordIndexImport.update({
    path: '/auth/forgot-password/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AppLayoutAppUserSaleIndexRoute = AppLayoutAppUserSaleIndexImport.update({
  path: '/app/user-sale/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAppUserMeSaleIndexRoute =
  AppLayoutAppUserMeSaleIndexImport.update({
    path: '/app/user-me-sale/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleBookingIndexRoute =
  AppLayoutAppUserMeSaleBookingIndexImport.update({
    path: '/app/user-me-sale-booking/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleBookingHistoryIndexRoute =
  AppLayoutAppUserMeSaleBookingHistoryIndexImport.update({
    path: '/app/user-me-sale-booking-history/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsIndexRoute = AppLayoutAppSettingsIndexImport.update({
  path: '/app/settings/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAppPremiumIndexRoute = AppLayoutAppPremiumIndexImport.update({
  path: '/app/premium/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAppPostIndexRoute = AppLayoutAppPostIndexImport.update({
  path: '/app/post/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAppNotificationIndexRoute =
  AppLayoutAppNotificationIndexImport.update({
    path: '/app/notification/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppContactUsIndexRoute = AppLayoutAppContactUsIndexImport.update(
  {
    path: '/app/contact-us/',
    getParentRoute: () => AppLayoutRoute,
  } as any,
)

const AppLayoutAppChatIndexRoute = AppLayoutAppChatIndexImport.update({
  path: '/app/chat/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAppCartIndexRoute = AppLayoutAppCartIndexImport.update({
  path: '/app/cart/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAppBookingIndexRoute = AppLayoutAppBookingIndexImport.update({
  path: '/app/booking/',
  getParentRoute: () => AppLayoutRoute,
} as any)

const AppLayoutAppBookingHistoryIndexRoute =
  AppLayoutAppBookingHistoryIndexImport.update({
    path: '/app/booking-history/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppProductProductLayoutRoute =
  AppLayoutAppProductProductLayoutImport.update({
    path: '/app/product/product-layout',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserSaleIdIndexRoute =
  AppLayoutAppUserSaleIdIndexImport.update({
    path: '/app/user-sale/$id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleCreateIndexRoute =
  AppLayoutAppUserMeSaleCreateIndexImport.update({
    path: '/app/user-me-sale/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleIdIndexRoute =
  AppLayoutAppUserMeSaleIdIndexImport.update({
    path: '/app/user-me-sale/$id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleBookingCreateIndexRoute =
  AppLayoutAppUserMeSaleBookingCreateIndexImport.update({
    path: '/app/user-me-sale-booking/create/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleBookingIdIndexRoute =
  AppLayoutAppUserMeSaleBookingIdIndexImport.update({
    path: '/app/user-me-sale-booking/$id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleBookingHistoryIdIndexRoute =
  AppLayoutAppUserMeSaleBookingHistoryIdIndexImport.update({
    path: '/app/user-me-sale-booking-history/$id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsWalletIndexRoute =
  AppLayoutAppSettingsWalletIndexImport.update({
    path: '/app/settings/wallet/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsUpdateIndexRoute =
  AppLayoutAppSettingsUpdateIndexImport.update({
    path: '/app/settings/update/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsTermsIndexRoute =
  AppLayoutAppSettingsTermsIndexImport.update({
    path: '/app/settings/terms/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsPolicyIndexRoute =
  AppLayoutAppSettingsPolicyIndexImport.update({
    path: '/app/settings/policy/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsOrderHistoryIndexRoute =
  AppLayoutAppSettingsOrderHistoryIndexImport.update({
    path: '/app/settings/order-history/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsLanguageIndexRoute =
  AppLayoutAppSettingsLanguageIndexImport.update({
    path: '/app/settings/language/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsChangePasswordIndexRoute =
  AppLayoutAppSettingsChangePasswordIndexImport.update({
    path: '/app/settings/change-password/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppProductProductLayoutIndexRoute =
  AppLayoutAppProductProductLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AppLayoutAppProductProductLayoutRoute,
  } as any)

const AppLayoutAppBookingIdIndexRoute = AppLayoutAppBookingIdIndexImport.update(
  {
    path: '/app/booking/$id/',
    getParentRoute: () => AppLayoutRoute,
  } as any,
)

const AppLayoutAppBookingHistoryIdIndexRoute =
  AppLayoutAppBookingHistoryIdIndexImport.update({
    path: '/app/booking-history/$id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppChatChatIdChatLayoutRoute =
  AppLayoutAppChatChatIdChatLayoutImport.update({
    path: '/app/chat/$chatId/chat-layout',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleIdEditIndexRoute =
  AppLayoutAppUserMeSaleIdEditIndexImport.update({
    path: '/app/user-me-sale/$id/edit/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleBookingIdEditIndexRoute =
  AppLayoutAppUserMeSaleBookingIdEditIndexImport.update({
    path: '/app/user-me-sale-booking/$id/edit/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppUserMeSaleBookingHistoryIdAcceptIndexRoute =
  AppLayoutAppUserMeSaleBookingHistoryIdAcceptIndexImport.update({
    path: '/app/user-me-sale-booking-history/$id/accept/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsWalletDepositIndexRoute =
  AppLayoutAppSettingsWalletDepositIndexImport.update({
    path: '/app/settings/wallet/deposit/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppSettingsOrderHistoryIdIndexRoute =
  AppLayoutAppSettingsOrderHistoryIdIndexImport.update({
    path: '/app/settings/order-history/$id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppProductProductLayoutIdIndexRoute =
  AppLayoutAppProductProductLayoutIdIndexImport.update({
    path: '/$id/',
    getParentRoute: () => AppLayoutAppProductProductLayoutRoute,
  } as any)

const AppLayoutAppPostUserIdIndexRoute =
  AppLayoutAppPostUserIdIndexImport.update({
    path: '/app/post/user/$id/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

const AppLayoutAppChatChatIdChatLayoutIndexRoute =
  AppLayoutAppChatChatIdChatLayoutIndexImport.update({
    path: '/',
    getParentRoute: () => AppLayoutAppChatChatIdChatLayoutRoute,
  } as any)

const AppLayoutAppBookingIdFormIndexRoute =
  AppLayoutAppBookingIdFormIndexImport.update({
    path: '/app/booking/$id/form/',
    getParentRoute: () => AppLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app-layout': {
      preLoaderRoute: typeof AppLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout': {
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout/auth/login': {
      preLoaderRoute: typeof AuthLayoutAuthLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_app-layout/app/': {
      preLoaderRoute: typeof AppLayoutAppIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/product/_product-layout': {
      preLoaderRoute: typeof AppLayoutAppProductProductLayoutImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/booking-history/': {
      preLoaderRoute: typeof AppLayoutAppBookingHistoryIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/booking/': {
      preLoaderRoute: typeof AppLayoutAppBookingIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/cart/': {
      preLoaderRoute: typeof AppLayoutAppCartIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/chat/': {
      preLoaderRoute: typeof AppLayoutAppChatIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/contact-us/': {
      preLoaderRoute: typeof AppLayoutAppContactUsIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/notification/': {
      preLoaderRoute: typeof AppLayoutAppNotificationIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/post/': {
      preLoaderRoute: typeof AppLayoutAppPostIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/premium/': {
      preLoaderRoute: typeof AppLayoutAppPremiumIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/settings/': {
      preLoaderRoute: typeof AppLayoutAppSettingsIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale-booking-history/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleBookingHistoryIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale-booking/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleBookingIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-sale/': {
      preLoaderRoute: typeof AppLayoutAppUserSaleIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_auth-layout/auth/forgot-password/': {
      preLoaderRoute: typeof AuthLayoutAuthForgotPasswordIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth-layout/auth/register/': {
      preLoaderRoute: typeof AuthLayoutAuthRegisterIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_app-layout/app/chat/$chatId/_chat-layout': {
      preLoaderRoute: typeof AppLayoutAppChatChatIdChatLayoutImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/booking-history/$id/': {
      preLoaderRoute: typeof AppLayoutAppBookingHistoryIdIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/booking/$id/': {
      preLoaderRoute: typeof AppLayoutAppBookingIdIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/product/_product-layout/': {
      preLoaderRoute: typeof AppLayoutAppProductProductLayoutIndexImport
      parentRoute: typeof AppLayoutAppProductProductLayoutImport
    }
    '/_app-layout/app/settings/change-password/': {
      preLoaderRoute: typeof AppLayoutAppSettingsChangePasswordIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/settings/language/': {
      preLoaderRoute: typeof AppLayoutAppSettingsLanguageIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/settings/order-history/': {
      preLoaderRoute: typeof AppLayoutAppSettingsOrderHistoryIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/settings/policy/': {
      preLoaderRoute: typeof AppLayoutAppSettingsPolicyIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/settings/terms/': {
      preLoaderRoute: typeof AppLayoutAppSettingsTermsIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/settings/update/': {
      preLoaderRoute: typeof AppLayoutAppSettingsUpdateIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/settings/wallet/': {
      preLoaderRoute: typeof AppLayoutAppSettingsWalletIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale-booking-history/$id/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleBookingHistoryIdIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale-booking/$id/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleBookingIdIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale-booking/create/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleBookingCreateIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale/$id/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleIdIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale/create/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleCreateIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-sale/$id/': {
      preLoaderRoute: typeof AppLayoutAppUserSaleIdIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/booking/$id/form/': {
      preLoaderRoute: typeof AppLayoutAppBookingIdFormIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/chat/$chatId/_chat-layout/': {
      preLoaderRoute: typeof AppLayoutAppChatChatIdChatLayoutIndexImport
      parentRoute: typeof AppLayoutAppChatChatIdChatLayoutImport
    }
    '/_app-layout/app/post/user/$id/': {
      preLoaderRoute: typeof AppLayoutAppPostUserIdIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/product/_product-layout/$id/': {
      preLoaderRoute: typeof AppLayoutAppProductProductLayoutIdIndexImport
      parentRoute: typeof AppLayoutAppProductProductLayoutImport
    }
    '/_app-layout/app/settings/order-history/$id/': {
      preLoaderRoute: typeof AppLayoutAppSettingsOrderHistoryIdIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/settings/wallet/deposit/': {
      preLoaderRoute: typeof AppLayoutAppSettingsWalletDepositIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale-booking-history/$id/accept/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleBookingHistoryIdAcceptIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale-booking/$id/edit/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleBookingIdEditIndexImport
      parentRoute: typeof AppLayoutImport
    }
    '/_app-layout/app/user-me-sale/$id/edit/': {
      preLoaderRoute: typeof AppLayoutAppUserMeSaleIdEditIndexImport
      parentRoute: typeof AppLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AppLayoutRoute.addChildren([
    AppLayoutAppIndexRoute,
    AppLayoutAppProductProductLayoutRoute.addChildren([
      AppLayoutAppProductProductLayoutIndexRoute,
      AppLayoutAppProductProductLayoutIdIndexRoute,
    ]),
    AppLayoutAppBookingHistoryIndexRoute,
    AppLayoutAppBookingIndexRoute,
    AppLayoutAppCartIndexRoute,
    AppLayoutAppChatIndexRoute,
    AppLayoutAppContactUsIndexRoute,
    AppLayoutAppNotificationIndexRoute,
    AppLayoutAppPostIndexRoute,
    AppLayoutAppPremiumIndexRoute,
    AppLayoutAppSettingsIndexRoute,
    AppLayoutAppUserMeSaleBookingHistoryIndexRoute,
    AppLayoutAppUserMeSaleBookingIndexRoute,
    AppLayoutAppUserMeSaleIndexRoute,
    AppLayoutAppUserSaleIndexRoute,
    AppLayoutAppChatChatIdChatLayoutRoute.addChildren([
      AppLayoutAppChatChatIdChatLayoutIndexRoute,
    ]),
    AppLayoutAppBookingHistoryIdIndexRoute,
    AppLayoutAppBookingIdIndexRoute,
    AppLayoutAppSettingsChangePasswordIndexRoute,
    AppLayoutAppSettingsLanguageIndexRoute,
    AppLayoutAppSettingsOrderHistoryIndexRoute,
    AppLayoutAppSettingsPolicyIndexRoute,
    AppLayoutAppSettingsTermsIndexRoute,
    AppLayoutAppSettingsUpdateIndexRoute,
    AppLayoutAppSettingsWalletIndexRoute,
    AppLayoutAppUserMeSaleBookingHistoryIdIndexRoute,
    AppLayoutAppUserMeSaleBookingIdIndexRoute,
    AppLayoutAppUserMeSaleBookingCreateIndexRoute,
    AppLayoutAppUserMeSaleIdIndexRoute,
    AppLayoutAppUserMeSaleCreateIndexRoute,
    AppLayoutAppUserSaleIdIndexRoute,
    AppLayoutAppBookingIdFormIndexRoute,
    AppLayoutAppPostUserIdIndexRoute,
    AppLayoutAppSettingsOrderHistoryIdIndexRoute,
    AppLayoutAppSettingsWalletDepositIndexRoute,
    AppLayoutAppUserMeSaleBookingHistoryIdAcceptIndexRoute,
    AppLayoutAppUserMeSaleBookingIdEditIndexRoute,
    AppLayoutAppUserMeSaleIdEditIndexRoute,
  ]),
  AuthLayoutRoute.addChildren([
    AuthLayoutAuthLoginRoute,
    AuthLayoutAuthForgotPasswordIndexRoute,
    AuthLayoutAuthRegisterIndexRoute,
  ]),
])
