// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SettingLayoutImport } from './routes/_setting-layout'
import { Route as LandlordLayoutImport } from './routes/_landlord-layout'
import { Route as AuthLayoutImport } from './routes/_auth-layout'
import { Route as IndexImport } from './routes/index'
import { Route as PayOkIndexImport } from './routes/pay-ok/index'
import { Route as SettingLayoutSettingIndexImport } from './routes/_setting-layout.setting/index'
import { Route as SettingLayoutSettingPasswordImport } from './routes/_setting-layout.setting/password'
import { Route as AuthLayoutAuthLoginImport } from './routes/_auth-layout.auth/login'
import { Route as SettingLayoutSettingWalletIndexImport } from './routes/_setting-layout.setting/wallet/index'
import { Route as AuthLayoutAuthRegisterIndexImport } from './routes/_auth-layout.auth/register/index'
import { Route as AuthLayoutAuthForgotPasswordIndexImport } from './routes/_auth-layout.auth/forgot-password/index'
import { Route as SettingLayoutSettingWalletWithdrawImport } from './routes/_setting-layout.setting/wallet/withdraw'
import { Route as SettingLayoutSettingWalletDepositImport } from './routes/_setting-layout.setting/wallet/deposit'

// Create/Update Routes

const SettingLayoutRoute = SettingLayoutImport.update({
  id: '/_setting-layout',
  getParentRoute: () => rootRoute,
} as any)

const LandlordLayoutRoute = LandlordLayoutImport.update({
  id: '/_landlord-layout',
  getParentRoute: () => rootRoute,
} as any)

const AuthLayoutRoute = AuthLayoutImport.update({
  id: '/_auth-layout',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PayOkIndexRoute = PayOkIndexImport.update({
  path: '/pay-ok/',
  getParentRoute: () => rootRoute,
} as any)

const SettingLayoutSettingIndexRoute = SettingLayoutSettingIndexImport.update({
  path: '/setting/',
  getParentRoute: () => SettingLayoutRoute,
} as any)

const SettingLayoutSettingPasswordRoute =
  SettingLayoutSettingPasswordImport.update({
    path: '/setting/password',
    getParentRoute: () => SettingLayoutRoute,
  } as any)

const AuthLayoutAuthLoginRoute = AuthLayoutAuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => AuthLayoutRoute,
} as any)

const SettingLayoutSettingWalletIndexRoute =
  SettingLayoutSettingWalletIndexImport.update({
    path: '/setting/wallet/',
    getParentRoute: () => SettingLayoutRoute,
  } as any)

const AuthLayoutAuthRegisterIndexRoute =
  AuthLayoutAuthRegisterIndexImport.update({
    path: '/auth/register/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const AuthLayoutAuthForgotPasswordIndexRoute =
  AuthLayoutAuthForgotPasswordIndexImport.update({
    path: '/auth/forgot-password/',
    getParentRoute: () => AuthLayoutRoute,
  } as any)

const SettingLayoutSettingWalletWithdrawRoute =
  SettingLayoutSettingWalletWithdrawImport.update({
    path: '/setting/wallet/withdraw',
    getParentRoute: () => SettingLayoutRoute,
  } as any)

const SettingLayoutSettingWalletDepositRoute =
  SettingLayoutSettingWalletDepositImport.update({
    path: '/setting/wallet/deposit',
    getParentRoute: () => SettingLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout': {
      preLoaderRoute: typeof AuthLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_landlord-layout': {
      preLoaderRoute: typeof LandlordLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_setting-layout': {
      preLoaderRoute: typeof SettingLayoutImport
      parentRoute: typeof rootRoute
    }
    '/pay-ok/': {
      preLoaderRoute: typeof PayOkIndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth-layout/auth/login': {
      preLoaderRoute: typeof AuthLayoutAuthLoginImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_setting-layout/setting/password': {
      preLoaderRoute: typeof SettingLayoutSettingPasswordImport
      parentRoute: typeof SettingLayoutImport
    }
    '/_setting-layout/setting/': {
      preLoaderRoute: typeof SettingLayoutSettingIndexImport
      parentRoute: typeof SettingLayoutImport
    }
    '/_setting-layout/setting/wallet/deposit': {
      preLoaderRoute: typeof SettingLayoutSettingWalletDepositImport
      parentRoute: typeof SettingLayoutImport
    }
    '/_setting-layout/setting/wallet/withdraw': {
      preLoaderRoute: typeof SettingLayoutSettingWalletWithdrawImport
      parentRoute: typeof SettingLayoutImport
    }
    '/_auth-layout/auth/forgot-password/': {
      preLoaderRoute: typeof AuthLayoutAuthForgotPasswordIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_auth-layout/auth/register/': {
      preLoaderRoute: typeof AuthLayoutAuthRegisterIndexImport
      parentRoute: typeof AuthLayoutImport
    }
    '/_setting-layout/setting/wallet/': {
      preLoaderRoute: typeof SettingLayoutSettingWalletIndexImport
      parentRoute: typeof SettingLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AuthLayoutRoute.addChildren([
    AuthLayoutAuthLoginRoute,
    AuthLayoutAuthForgotPasswordIndexRoute,
    AuthLayoutAuthRegisterIndexRoute,
  ]),
  LandlordLayoutRoute,
  SettingLayoutRoute.addChildren([
    SettingLayoutSettingPasswordRoute,
    SettingLayoutSettingIndexRoute,
    SettingLayoutSettingWalletDepositRoute,
    SettingLayoutSettingWalletWithdrawRoute,
    SettingLayoutSettingWalletIndexRoute,
  ]),
  PayOkIndexRoute,
])
